### ISSUE TITLE
extend order definition and functionality (endpoints)

### ISSUE THREAD

**Issue by askmike** [Guruvest/bridge-api#1]
Right now the `Order` definition is missing a rate (price), which is quite important. 

Related there is an endpoint to create an order (`POST /market/order`), but no endpoint to cancel one. Lastly an endpoint to move an order would be great as well (though not all exchanges natively support this).

**Comment by lucamerolla** [comment]
About canceling the order. the endpoint to be used is:
"/market/order/{orderId}" with the DELETE method
